### ISSUE TITLE
Get ud_pingpong.c compiling

### ISSUE THREAD

**Issue by sungeunchoi** [ofi-cray/fabtests-cray#24]
CLOCK_REALTIME_COARSE (added by https://github.com/ofiwg/fabtests/pull/269)  is unavailable.

**Comment by hppritcha** [comment]
i'll take this.

**Comment by hppritcha** [comment]
I observe the same build error on edison: 

hpp@edison12:~/fabtests-cray> (master)cat /etc/opt/cray/release/CLEinfo
CLERELEASE=5.2.UP03
INSTALLERVERSION=d07
LUSTRE=yes
NETWORK=ari
XTRELEASE=5.2.56

**Comment by hppritcha** [comment]
looks like simple use of CLOCK_REALTIME messes up something so the fabtest doesn't work anymore.

**Comment by sungeunchoi** [comment]
Is this the general timeout mechanism that's causing the problem?  The test passed the last few times.
